version: '3.8'

services:
  web:
    build: .
    container_name: feedback-analyzer
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
      - SECRET_KEY=${SECRET_KEY:-change-me-in-production}
    volumes:
      - ./models:/app/models:ro
      - ./dataset:/app/dataset:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: feedback-network
